"""added mpeas number clumn to membership

Revision ID: 8e78ff7e7f00
Revises: 8752a54a531c
Create Date: 2024-02-27 02:05:05.726274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e78ff7e7f00'
down_revision = '8752a54a531c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('mpesa_number')

    # ### end Alembic commands ###
